UPDATE shows SET title = "How I Met Your Mother" WHERE title = "How i met your mother";
UPDATE shows SET title = "Adventure Time" WHERE title LIKE "%adventure time%";
UPDATE shows SET title = "Arrow" WHERE title LIKE "%arrow%";
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title LIKE "%avatar%last airbender";
UPDATE shows SET title = "Brooklyn Nine-Nine" WHERE title LIKE "%b%9%9";
UPDATE shows SET title = "Game of Thrones" WHERE title LIKE "got";
UPDATE shows SET title = "Game of Thrones" WHERE title LIKE "game of thrones";
UPDATE shows SET title = "Grey’s Anatomy" WHERE title LIKE "grey%anatomy";
UPDATE shows SET title = "Community" WHERE title LIKE "Community";
UPDATE shows SET title = "Friends" WHERE title LIKE "friend%";
UPDATE shows SET title = "Gilmore Girls" WHERE title LIKE "gilmore%girl%";
UPDATE shows SET title = "How I Met Your Mother" WHERE title LIKE "how%i%met%your%mother";
UPDATE shows SET title = "How I Met Your Mother" WHERE title LIKE "himym";
UPDATE shows SET title = "It’s Always Sunny in Philadelphia" WHERE title LIKE "it%s always sunny in phil";
UPDATE shows SET title = "Parks and Recreation" WHERE title LIKE "parks % rec%";
UPDATE shows SET title = "Sherlock" WHERE title LIKE "sherlock%";
UPDATE shows SET title = "Squid Game" WHERE title LIKE "squid game";
UPDATE shows SET title = "The Bachelorette" WHERE title LIKE "%bachelorette";
UPDATE shows SET title = "The Crown" WHERE title LIKE "the crown";
UPDATE shows SET title = "The Office" WHERE title LIKE "the office";
UPDATE shows SET title = "The Queen's Gambit" WHERE title LIKE "queen%s gambit";
UPDATE shows SET title = "The Untamed" WHERE title LIKE "%untamed";
UPDATE shows SET title = "Squid Game" WHERE title LIKE "squid game";
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title LIKE "avatar the last airbender";
UPDATE shows SET title = "Billions" WHERE title LIKE "billions";
UPDATE shows SET title = "Criminal Minds" WHERE title LIKE "criminal minds";
UPDATE shows SET title = "Family Guy" WHERE title LIKE "family guy";
UPDATE shows SET title = "The Office" WHERE title LIKE "%office";
UPDATE shows SET title = "Grey's Anatomy" WHERE title LIKE "%anatomy";
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title LIKE "%the last airbender";
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title LIKE "avatar%";
SELECT * FROM shows ORDER BY title;

-- not sure why Grey's anatomy did not update properly. Decided to ignore it....